language: objective-c
cache: cocoapods # pod install somtimes takes >20 minutes, so lets cache this

osx_image: xcode8

before_install:
    - brew update # we may not be running the latest version so always update
    - brew outdated xctool || brew upgrade xctool # only upgrade if outdated (saves 2 minutes)
    - gem install cocoapods # get the latest cocoapods
    - gem install xcpretty
    - pod repo update --silent # log output is too long without --silent

install: travis_wait 30 pod install # OpenSSL takes a long time to compile

script:
- |
  set -o pipefail
  # default xctool was hanging. see https://github.com/travis-ci/travis-ci/issues/3986
  xcodebuild -workspace Signal.xcworkspace -scheme Signal \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' \
    build test | xcpretty

